version: '3'
services:
  web:
    container_name: lib_web
    build: ./docker/nginx
    ports:
        - 80:80
    depends_on:
        - php-fpm
    volumes:
      - .:/var/www/html/
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
 
  php-fpm:
    container_name: lib_php
    build: ./docker/php
    volumes:
        - ./:/var/www/html